language: php
before_install:
  - sudo apt-get install zend-framework-bin
before_script:
  - zf create project .
  - zf enable layout
  - wget --no-check-certificate https://github.com/muiku/h5bp-zendframework/tarball/zfint -O - | tar -xvz --strip 1
script: ant -buildfile public/build/build.xml
