language: php
php: 5.4
before_install:
  - wget http://www.apache.org/dist/ant/binaries/apache-ant-1.8.3-bin.tar.gz -O - | tar -xz
  - wget http://framework.zend.com/releases/ZendFramework-1.11.11/ZendFramework-1.11.11-minimal.tar.gz -O - | tar -xz
before_script:
  - export PATH=$PWD/apache-ant-1.8.3/bin:$PWD/ZendFramework-1.11.11-minimal/bin:$PATH
  - ant -version
  - zf.sh show version
  - zf.sh create project .
  - zf.sh enable layout
  - ln -s ~/ZendFramework-1.11.11-minimal/library/Zend library/Zend
  - wget --no-check-certificate https://github.com/muiku/h5bp-zendframework/tarball/zfint -O - | tar -xvz --strip 1
  - sed -ie 's/layouts\/scripts/layouts\/scripts\/publish/g' application/configs/application.ini
script:
  - ant -buildfile public/build/build.xml
# - phpunit --configuration tests/phpunit.xml
notifications:
  email: false
