language: php

before_install:
  - sudo apt-get -qq install zend-framework-bin
  - wget http://www.apache.org/dist/ant/binaries/apache-ant-1.8.3-bin.tar.gz
  - tar -zxvf apache-ant-1.8.3-bin.tar.gz
  - export PATH=~/apache-ant-1.8.3/bin:$PATH

before_script:
  - ant -version
  - zf show version
  - zf create project .
  - zf enable layout
  - wget --no-check-certificate https://github.com/muiku/h5bp-zendframework/tarball/zfint -O - | tar -xvz --strip 1

script: ant -buildfile public/build/build.xml
